import { Building2, Edit3, Mail, MapPin, Phone, Plus, Search, ShieldAlert, X } from 'lucide-react'
import { type FormEvent, useMemo, useState } from 'react'
import { useEventFlowData } from '../hooks/useEventFlowData.tsx'
import { useToast } from '../hooks/useToast.tsx'
import type { Contractor, ContractorType } from '../types/index.ts'

const contractorTypes: ContractorType[] = ['Отель', 'Ресторан', 'Площадка', 'Трансфер', 'Кейтеринг', 'Оборудование', 'Подрядчик', 'Другое']
const emptyContractor: Contractor = { id: '', name: '', type: 'Площадка', city: '', contactPerson: '', phone: '', email: '', legalEntity: '', vatInfo: '', serviceFee: '', paymentTerms: '', cancellationTerms: '', notes: '', lastVerifiedAt: '' }

function isStale(value: string) { if (!value) return true; return (Date.now() - new Date(`${value}T12:00:00`).getTime()) / 86_400_000 > 60 }

export function ContractorsPage() {
  const { contractors, saveContractor } = useEventFlowData()
  const { showToast } = useToast()
  const [query, setQuery] = useState('')
  const [editing, setEditing] = useState<Contractor | null>(null)
  const filtered = useMemo(() => contractors.filter((contractor) => `${contractor.name} ${contractor.type} ${contractor.city} ${contractor.contactPerson}`.toLowerCase().includes(query.toLowerCase())), [contractors, query])
  return <main className="page"><div className="page-toolbar"><div><h1>Контрагенты</h1><p>Площадки, отели и подрядчики с датой последней проверки условий</p></div><button className="primary-button" onClick={() => setEditing({ ...emptyContractor, id: `contractor-${Date.now()}` })}><Plus size={18} />Добавить контрагента</button></div>{editing && <ContractorForm contractor={editing} onCancel={() => setEditing(null)} onSave={(contractor) => { saveContractor(contractor); setEditing(null); showToast('Контрагент сохранён') }} />}<section className="card contractors-panel"><label className="events-search"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Поиск по названию, типу, городу или контакту" /></label><div className="contractor-grid">{filtered.map((contractor) => <article className="contractor-card" key={contractor.id}><div className="contractor-card-head"><span><Building2 size={20} /></span><div><h2>{contractor.name}</h2><p>{contractor.type}</p></div><button className="icon-button" onClick={() => setEditing(contractor)} aria-label="Редактировать"><Edit3 size={17} /></button></div><div className="contractor-details"><span><MapPin size={15} />{contractor.city || 'Город не указан'}</span><span><Phone size={15} />{contractor.phone || 'Телефон не указан'}</span><span><Mail size={15} />{contractor.email || 'Email не указан'}</span></div><dl><div><dt>Контакт</dt><dd>{contractor.contactPerson || '—'}</dd></div><div><dt>НДС</dt><dd>{contractor.vatInfo || '—'}</dd></div><div><dt>Сервисный сбор</dt><dd>{contractor.serviceFee || '—'}</dd></div></dl>{isStale(contractor.lastVerifiedAt) ? <div className="stale-warning"><ShieldAlert size={15} /><span>Требуется подтверждение актуальных условий</span></div> : <div className="verified-note">Проверено {new Intl.DateTimeFormat('ru-RU').format(new Date(`${contractor.lastVerifiedAt}T12:00:00`))}</div>}</article>)}</div>{!filtered.length && <div className="empty-state"><Search size={30} /><h2>Контрагенты не найдены</h2><p>Измените запрос или добавьте новую запись.</p></div>}</section></main>
}

function ContractorForm({ contractor, onCancel, onSave }: { contractor: Contractor; onCancel: () => void; onSave: (contractor: Contractor) => void }) {
  const [form, setForm] = useState(contractor)
  const submit = (e: FormEvent) => { e.preventDefault(); onSave(form) }
  return <form className="card contractor-form" onSubmit={submit}><div className="section-title"><div><Building2 className="section-blue" size={22} /><h2>{contractor.name ? 'Редактировать контрагента' : 'Новый контрагент'}</h2></div><button type="button" className="icon-button" onClick={onCancel}><X size={18} /></button></div><div className="form-grid contractor-form-grid"><label><span>Название</span><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span>Тип</span><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as ContractorType })}>{contractorTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label><span>Город</span><input value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /></label><label><span>Контактное лицо</span><input value={form.contactPerson} onChange={(e) => setForm({ ...form, contactPerson: e.target.value })} /></label><label><span>Телефон</span><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label><span>Email</span><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label><span>Юридическое лицо</span><input value={form.legalEntity} onChange={(e) => setForm({ ...form, legalEntity: e.target.value })} /></label><label><span>НДС</span><input value={form.vatInfo} onChange={(e) => setForm({ ...form, vatInfo: e.target.value })} placeholder="Например, НДС 20%" /></label><label><span>Сервисный сбор</span><input value={form.serviceFee} onChange={(e) => setForm({ ...form, serviceFee: e.target.value })} /></label><label><span>Проверено</span><input type="date" value={form.lastVerifiedAt} onChange={(e) => setForm({ ...form, lastVerifiedAt: e.target.value })} /></label><label className="full-field"><span>Условия оплаты</span><textarea value={form.paymentTerms} onChange={(e) => setForm({ ...form, paymentTerms: e.target.value })} /></label><label className="full-field"><span>Условия отмены</span><textarea value={form.cancellationTerms} onChange={(e) => setForm({ ...form, cancellationTerms: e.target.value })} /></label><label className="full-field"><span>Заметки</span><textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><div className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Отмена</button><button className="primary-button">Сохранить контрагента</button></div></form>
}
