import { CheckCircle2, CircleHelp, Plus, Search } from 'lucide-react'
import { type FormEvent, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useEventFlowData } from '../hooks/useEventFlowData.tsx'
import { useToast } from '../hooks/useToast.tsx'
import type { OpenQuestion, Priority, QuestionStatus } from '../types/index.ts'
import { deadlineLabel, getDeadlineState } from '../utils/dates.ts'

const statusLabels: Record<QuestionStatus, string> = { open: 'Открыт', waiting_external: 'Ждём контрагента', waiting_client: 'Ждём клиента', resolved: 'Решён' }

export function QuestionsPage() {
  const { events, questions, addQuestion, updateQuestion } = useEventFlowData()
  const { showToast } = useToast()
  const [query, setQuery] = useState('')
  const [showResolved, setShowResolved] = useState(false)
  const [adding, setAdding] = useState(false)
  const filtered = useMemo(() => questions.filter((question) => (showResolved || question.status !== 'resolved') && `${question.title} ${question.description} ${question.responsibleParty}`.toLowerCase().includes(query.toLowerCase())), [questions, query, showResolved])
  return <main className="page"><div className="page-toolbar"><div><h1>Открытые вопросы</h1><p>Вопросы, по которым нужен ответ или решение</p></div><button className="primary-button" onClick={() => setAdding(true)}><Plus size={18} />Добавить вопрос</button></div>{adding && <GlobalQuestionForm events={events} onCancel={() => setAdding(false)} onSave={(question) => { addQuestion(question); setAdding(false); showToast('Вопрос добавлен') }} />}<section className="card questions-page-card"><div className="questions-toolbar"><label className="events-search"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Поиск по вопросам и ответственным" /></label><label className="toggle-label"><input type="checkbox" checked={showResolved} onChange={(e) => setShowResolved(e.target.checked)} />Показывать решённые</label></div><div className="questions-table"><div className="questions-table-head"><span>Вопрос</span><span>Мероприятие</span><span>Ответственный</span><span>Дедлайн</span><span>Статус</span></div>{filtered.map((question) => { const event = events.find((item) => item.id === question.eventId); const deadlineState = getDeadlineState(question.deadline); return <article className={`questions-table-row ${question.status === 'resolved' ? 'resolved' : ''}`} key={question.id}><div><span className={`question-priority priority-${question.priority}`}><CircleHelp size={15} /></span><span><strong>{question.title}</strong><small>{question.description}</small></span></div><div>{event ? <Link to={`/events/${event.id}`}>{event.title}</Link> : '—'}</div><div>{question.responsibleParty}</div><div className={deadlineState === 'overdue' ? 'deadline-overdue' : ''}>{deadlineLabel(question.deadline)}</div><div><select value={question.status} onChange={(e) => updateQuestion({ ...question, status: e.target.value as QuestionStatus, resolvedAt: e.target.value === 'resolved' ? new Date().toISOString() : null })}>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div></article> })}</div>{!filtered.length && <div className="empty-state"><CheckCircle2 size={30} /><h2>Нет открытых вопросов</h2><p>Всё важное на данный момент закрыто.</p></div>}</section></main>
}

function GlobalQuestionForm({ events, onCancel, onSave }: { events: ReturnType<typeof useEventFlowData>['events']; onCancel: () => void; onSave: (question: OpenQuestion) => void }) {
  const [form, setForm] = useState({ eventId: events[0]?.id ?? '', title: '', description: '', responsibleParty: '', deadline: '', priority: 'high' as Priority })
  const submit = (e: FormEvent) => { e.preventDefault(); onSave({ id: `question-${Date.now()}`, eventId: form.eventId, title: form.title, description: form.description, responsibleParty: form.responsibleParty, deadline: form.deadline || null, priority: form.priority, status: 'open', createdAt: new Date().toISOString(), resolvedAt: null }) }
  return <form className="card global-question-form" onSubmit={submit}><div className="section-title"><div><CircleHelp className="section-blue" size={22} /><h2>Новый вопрос</h2></div></div><div className="form-grid"><label><span>Мероприятие</span><select required value={form.eventId} onChange={(e) => setForm({ ...form, eventId: e.target.value })}>{events.map((event) => <option key={event.id} value={event.id}>{event.title}</option>)}</select></label><label><span>Ответственный</span><input required value={form.responsibleParty} onChange={(e) => setForm({ ...form, responsibleParty: e.target.value })} placeholder="Клиент, площадка, подрядчик" /></label><label className="full-field"><span>Вопрос</span><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label className="full-field"><span>Описание</span><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label><span>Дедлайн</span><input type="date" value={form.deadline} onChange={(e) => setForm({ ...form, deadline: e.target.value })} /></label><label><span>Приоритет</span><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value as Priority })}><option value="normal">Обычный</option><option value="high">Высокий</option><option value="critical">Критичный</option></select></label></div><div className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Отмена</button><button className="primary-button">Добавить</button></div></form>
}
